AWSTemplateFormatVersion: 2010-09-09

Parameters:
 
 aInstanceType: 
  Type: String
  Default: t2.small 
  AllowedValues:
   - t2.micro
   - t2.small
   - t2.medium 
  Description: Choose type for your instance.

 aKeyName:
  Type: AWS::EC2::KeyPair::KeyName
  Default: Jenkins
  Description: Amazon EC2 key pair. 

Resources:

 aLaunchTemplate:
  Type: AWS::EC2::LaunchTemplate
  Properties:
   LaunchTemplateData:
    InstanceType: !Ref aInstanceType
    KeyName: !Ref aKeyName
    ImageId: ami-098f16afa9edf40be
    TagSpecifications:
      - ResourceType: instance
        Tags:
         - Key: Environment
           Value: Test
   LaunchTemplateName: linux


 aInstanceOne:
  Type: AWS::EC2::Instance 
  Properties: 
   LaunchTemplate:
    LaunchTemplateId: !Ref aLaunchTemplate
    Version: 1
   UserData:
    Fn::Base64:
      !Sub | 
        #!/bin/bash
        yum update -y 
        yum install wget -y 
        wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins.io/redhat-stable/jenkins.repo
        rpm --import http://pkg.jenkins.io/redhat-stable/jenkins.io.key
        yum install jenkins java-1.8.0-openjdk -y
        systemctl start jenkins
        systemctl enable jenkins

 aInstanceTwo:
  Type: AWS::EC2::Instance 
  Properties: 
   LaunchTemplate:
    LaunchTemplateId: !Ref aLaunchTemplate
    Version: 1

 aInstanceThree:
  Type: AWS::EC2::Instance 
  Properties: 
   LaunchTemplate:
    LaunchTemplateId: !Ref aLaunchTemplate
    Version: 1      

